version: 0.2

env:
  variables:
    AWS_REGION: us-east-1                  # your AWS region
    ECR_REPO_URI: 230027225622.dkr.ecr.us-east-1.amazonaws.com/pawan/product-config

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Maven..."
      - mvn -version
      - aws --version
      - docker --version

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - export IMAGE_TAG=$CODEBUILD_BUILD_NUMBER
      - echo "IMAGE_TAG=$IMAGE_TAG"
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI

  build:
    commands:
      - echo "Building Maven project..."
      - mvn clean package -DskipTests
      - echo "Building Docker image..."
      - docker build -t backend .
      - docker tag backend:latest $ECR_REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_REPO_URI:$IMAGE_TAG
      - echo "Build and push completed successfully!"
      - echo "Creating imagedefinitions.json for ECS deploy..."
      - printf '[{"name":"product-config","imageUri":"%s:%s"}]' $ECR_REPO_URI $IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

cache:
  paths:
    - '/root/.m2/**/*'